<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSIPEVwI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSIPEVwI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSIPEVwI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSIPEVwI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSIPEVwI\App_KernelDevDebugContainer([
    'container.build_hash' => 'SIPEVwI',
    'container.build_id' => 'fde58ca7',
    'container.build_time' => 1626072083,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSIPEVwI');
