<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container91Pazr0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container91Pazr0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container91Pazr0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container91Pazr0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container91Pazr0\App_KernelDevDebugContainer([
    'container.build_hash' => '91Pazr0',
    'container.build_id' => '5f2aecc9',
    'container.build_time' => 1626243367,
], __DIR__.\DIRECTORY_SEPARATOR.'Container91Pazr0');
