<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerETzr9s8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerETzr9s8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerETzr9s8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerETzr9s8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerETzr9s8\App_KernelDevDebugContainer([
    'container.build_hash' => 'ETzr9s8',
    'container.build_id' => '602f2164',
    'container.build_time' => 1626068842,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerETzr9s8');
