<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'categories' => [[], ['_controller' => 'App\\Controller\\CategoryController::getCategories'], [], [['text', '/categories']], [], []],
    'get_category' => [['id'], ['_controller' => 'App\\Controller\\CategoryController::getCategory'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/categories']], [], []],
    'create_category' => [[], ['_controller' => 'App\\Controller\\CategoryController::createCategory'], ['id' => '\\d+'], [['text', '/categories']], [], []],
    'update_category' => [['id'], ['_controller' => 'App\\Controller\\CategoryController::updateCategory'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/categories']], [], []],
    'delete_category' => [['id'], ['_controller' => 'App\\Controller\\CategoryController::deleteCategory'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/categories']], [], []],
    'tickets' => [[], ['_controller' => 'App\\Controller\\TicketController::getTickets'], [], [['text', '/tickets']], [], []],
    'show_ticket' => [['id'], ['_controller' => 'App\\Controller\\TicketController::showTicket'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/tickets']], [], []],
    'create_ticket' => [[], ['_controller' => 'App\\Controller\\TicketController::createTicket'], [], [['text', '/tickets']], [], []],
    'update_ticket' => [['id'], ['_controller' => 'App\\Controller\\TicketController::updateTicket'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/tickets']], [], []],
    'delete_ticket' => [['id'], ['_controller' => 'App\\Controller\\TicketController::deleteTicket'], ['id' => '\\d+'], [['variable', '/', '\\d+', 'id', true], ['text', '/tickets']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
