<?php

namespace Container84lbpzc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E5h8VvlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.e5h8Vvl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.e5h8Vvl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'request' => ['privates', '.errored.dC0Ipi1', NULL, 'Cannot determine controller argument for "App\\Controller\\TicketController::getTickets()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\Request". Did you forget to add a use statement?'],
            'ticketRepository' => ['privates', 'App\\Repository\\TicketRepository', 'getTicketRepositoryService', true],
        ], [
            'request' => '?',
            'ticketRepository' => 'App\\Repository\\TicketRepository',
        ]);
    }
}
