<?php

namespace Container91Pazr0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1kbeQbSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1kbeQbS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1kbeQbS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CategoryController::createCategory' => ['privates', '.service_locator.O7Avvig', 'get_ServiceLocator_O7AvvigService', true],
            'App\\Controller\\CategoryController::getCategories' => ['privates', '.service_locator.uCSWYWR', 'get_ServiceLocator_UCSWYWRService', true],
            'App\\Controller\\CategoryController::updateCategory' => ['privates', '.service_locator.O7Avvig', 'get_ServiceLocator_O7AvvigService', true],
            'App\\Controller\\TicketController::createTicket' => ['privates', '.service_locator.O7Avvig', 'get_ServiceLocator_O7AvvigService', true],
            'App\\Controller\\TicketController::getTickets' => ['privates', '.service_locator.1.Dl96P', 'get_ServiceLocator_1_Dl96PService', true],
            'App\\Controller\\TicketController::updateTicket' => ['privates', '.service_locator.O7Avvig', 'get_ServiceLocator_O7AvvigService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\CategoryController:createCategory' => ['privates', '.service_locator.O7Avvig', 'get_ServiceLocator_O7AvvigService', true],
            'App\\Controller\\CategoryController:getCategories' => ['privates', '.service_locator.uCSWYWR', 'get_ServiceLocator_UCSWYWRService', true],
            'App\\Controller\\CategoryController:updateCategory' => ['privates', '.service_locator.O7Avvig', 'get_ServiceLocator_O7AvvigService', true],
            'App\\Controller\\TicketController:createTicket' => ['privates', '.service_locator.O7Avvig', 'get_ServiceLocator_O7AvvigService', true],
            'App\\Controller\\TicketController:getTickets' => ['privates', '.service_locator.1.Dl96P', 'get_ServiceLocator_1_Dl96PService', true],
            'App\\Controller\\TicketController:updateTicket' => ['privates', '.service_locator.O7Avvig', 'get_ServiceLocator_O7AvvigService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\CategoryController::createCategory' => '?',
            'App\\Controller\\CategoryController::getCategories' => '?',
            'App\\Controller\\CategoryController::updateCategory' => '?',
            'App\\Controller\\TicketController::createTicket' => '?',
            'App\\Controller\\TicketController::getTickets' => '?',
            'App\\Controller\\TicketController::updateTicket' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CategoryController:createCategory' => '?',
            'App\\Controller\\CategoryController:getCategories' => '?',
            'App\\Controller\\CategoryController:updateCategory' => '?',
            'App\\Controller\\TicketController:createTicket' => '?',
            'App\\Controller\\TicketController:getTickets' => '?',
            'App\\Controller\\TicketController:updateTicket' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
